In [1]:
from explann_doe import fullfact, ff2n, ccdesign

In [2]:
fullfact([2,2,2,2])

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 1., 1., 0.],
       [1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 0., 1.],
       [1., 1., 0., 1.],
       [0., 0., 1., 1.],
       [1., 0., 1., 1.],
       [0., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [3]:
ff2n(4)

array([[-1., -1., -1., -1.],
       [ 1., -1., -1., -1.],
       [-1.,  1., -1., -1.],
       [ 1.,  1., -1., -1.],
       [-1., -1.,  1., -1.],
       [ 1., -1.,  1., -1.],
       [-1.,  1.,  1., -1.],
       [ 1.,  1.,  1., -1.],
       [-1., -1., -1.,  1.],
       [ 1., -1., -1.,  1.],
       [-1.,  1., -1.,  1.],
       [ 1.,  1., -1.,  1.],
       [-1., -1.,  1.,  1.],
       [ 1., -1.,  1.,  1.],
       [-1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [4]:
ccd_levels = ccdesign(5, center=(0,1), face='ccc')
ccd_levels

array([[-1.        , -1.        , -1.        , -1.        , -1.        ],
       [ 1.        , -1.        , -1.        , -1.        , -1.        ],
       [-1.        ,  1.        , -1.        , -1.        , -1.        ],
       [ 1.        ,  1.        , -1.        , -1.        , -1.        ],
       [-1.        , -1.        ,  1.        , -1.        , -1.        ],
       [ 1.        , -1.        ,  1.        , -1.        , -1.        ],
       [-1.        ,  1.        ,  1.        , -1.        , -1.        ],
       [ 1.        ,  1.        ,  1.        , -1.        , -1.        ],
       [-1.        , -1.        , -1.        ,  1.        , -1.        ],
       [ 1.        , -1.        , -1.        ,  1.        , -1.        ],
       [-1.        ,  1.        , -1.        ,  1.        , -1.        ],
       [ 1.        ,  1.        , -1.        ,  1.        , -1.        ],
       [-1.        , -1.        ,  1.        ,  1.        , -1.        ],
       [ 1.        , -1.        ,  1. 

In [5]:
import numpy as np

In [6]:
levels = np.array([-2.34520788,-1,0,1,2.34520788])

# variables ranges
Thickness = (0.001, 0.010)
CP3_y = (-0.01255805, 0.0)
T0in = (400, 800)
p0in = (4.0e5, 1.0e6)
outerTemperature = (290, 400)

Thickness_levels = np.interp(levels, (levels.min(), levels.max()), Thickness)
CP3_y_levels = np.interp(levels, (levels.min(), levels.max()), CP3_y)
T0in_levels = np.interp(levels, (levels.min(), levels.max()), T0in)
p0in_lebels = np.interp(levels, (levels.min(), levels.max()), p0in)
outerTemperature_levels = np.interp(levels, (levels.min(), levels.max()), outerTemperature)

In [7]:
outerTemperature_levels

array([290.       , 321.5479212, 345.       , 368.4520788, 400.       ])

In [8]:
np.set_printoptions(precision=5, suppress=True)

converted_levels = np.array(
    [Thickness_levels,
     CP3_y_levels,
     T0in_levels,
     p0in_lebels,
     outerTemperature_levels,]
)
converted_levels.shape
converted_levels

array([[      0.001  ,       0.00358,       0.0055 ,       0.00742,
              0.01   ],
       [     -0.01256,      -0.00896,      -0.00628,      -0.0036 ,
              0.     ],
       [    400.     ,     514.71971,     600.     ,     685.28029,
            800.     ],
       [ 400000.     ,  572079.57019,  700000.     ,  827920.42981,
        1000000.     ],
       [    290.     ,     321.54792,     345.     ,     368.45208,
            400.     ]])

In [9]:
Thickness_levels

array([0.001  , 0.00358, 0.0055 , 0.00742, 0.01   ])

In [10]:
levels*(Thickness_levels[-2]-np.mean(Thickness_levels)) + np.mean(Thickness_levels)

array([0.001  , 0.00358, 0.0055 , 0.00742, 0.01   ])

In [11]:
ccd_levels_converted = np.copy(ccd_levels)
for i in range(ccd_levels.shape[1]):
    ccd_levels_converted[:,i] = ccd_levels[:,i]*(converted_levels[i][-2]-np.mean(converted_levels[i])) + np.mean(converted_levels[i])


In [12]:
np.set_printoptions(precision=5, suppress=True)
print(ccd_levels_converted)

[[     0.00358     -0.00896    514.71971 572079.57019    321.54792]
 [     0.00742     -0.00896    514.71971 572079.57019    321.54792]
 [     0.00358     -0.0036     514.71971 572079.57019    321.54792]
 [     0.00742     -0.0036     514.71971 572079.57019    321.54792]
 [     0.00358     -0.00896    685.28029 572079.57019    321.54792]
 [     0.00742     -0.00896    685.28029 572079.57019    321.54792]
 [     0.00358     -0.0036     685.28029 572079.57019    321.54792]
 [     0.00742     -0.0036     685.28029 572079.57019    321.54792]
 [     0.00358     -0.00896    514.71971 827920.42981    321.54792]
 [     0.00742     -0.00896    514.71971 827920.42981    321.54792]
 [     0.00358     -0.0036     514.71971 827920.42981    321.54792]
 [     0.00742     -0.0036     514.71971 827920.42981    321.54792]
 [     0.00358     -0.00896    685.28029 827920.42981    321.54792]
 [     0.00742     -0.00896    685.28029 827920.42981    321.54792]
 [     0.00358     -0.0036     685.28029 827920.

In [13]:
ccd_levels_converted_ids = np.concatenate([np.arange(1,ccd_levels_converted.shape[0]+1)[:,None],ccd_levels_converted], axis=1)

In [14]:
np.savetxt('ccd_experiment.txt',ccd_levels_converted,delimiter=',')

In [15]:
import pandas as pd

ccd_levels_converted_ids_dataframe = pd.DataFrame(data=ccd_levels_converted_ids, columns=['ID','Thickness','CP3_y','T0in','p0in','outerTemperature'])
ccd_levels_converted_ids_dataframe.to_csv('doe_experimental_planning.txt', sep=',', index=False)
ccd_levels_converted_ids_dataframe

ID  Thickness         CP3_y        T0in           p0in  outerTemperature
0    1.0   0.003581 -8.956410e-03  514.719713  572079.570191        321.547921
1    2.0   0.007419 -8.956410e-03  514.719713  572079.570191        321.547921
2    3.0   0.003581 -3.601640e-03  514.719713  572079.570191        321.547921
3    4.0   0.007419 -3.601640e-03  514.719713  572079.570191        321.547921
4    5.0   0.003581 -8.956410e-03  685.280287  572079.570191        321.547921
5    6.0   0.007419 -8.956410e-03  685.280287  572079.570191        321.547921
6    7.0   0.003581 -3.601640e-03  685.280287  572079.570191        321.547921
7    8.0   0.007419 -3.601640e-03  685.280287  572079.570191        321.547921
8    9.0   0.003581 -8.956410e-03  514.719713  827920.429809        321.547921
9   10.0   0.007419 -8.956410e-03  514.719713  827920.429809        321.547921
10  11.0   0.003581 -3.601640e-03  514.719713  827920.429809        321.547921
11  12.0   0.007419 -3.601640e-03  514.719713  827920.429809        321.547921
12  13.0   0.003581 -8.956410e-03  685.280287  827920.429809        321.547921
13  14.0   0.007419 -8.956410e-03  685.280287  827920.429809        321.547921
14  15.0   0.003581 -3.601640e-03  685.280287  827920.429809        321.547921
15  16.0   0.007419 -3.601640e-03  685.280287  827920.429809        321.547921
16  17.0   0.003581 -8.956410e-03  514.719713  572079.570191        368.452079
17  18.0   0.007419 -8.956410e-03  514.719713  572079.570191        368.452079
18  19.0   0.003581 -3.601640e-03  514.719713  572079.570191        368.452079
19  20.0   0.007419 -3.601640e-03  514.719713  572079.570191        368.452079
20  21.0   0.003581 -8.956410e-03  685.280287  572079.570191        368.452079
21  22.0   0.007419 -8.956410e-03  685.280287  572079.570191        368.452079
22  23.0   0.003581 -3.601640e-03  685.280287  572079.570191        368.452079
23  24.0   0.007419 -3.601640e-03  685.280287  572079.570191        368.452079
24  25.0   0.003581 -8.956410e-03  514.719713  827920.429809        368.452079
25  26.0   0.007419 -8.956410e-03  514.719713  827920.429809        368.452079
26  27.0   0.003581 -3.601640e-03  514.719713  827920.429809        368.452079
27  28.0   0.007419 -3.601640e-03  514.719713  827920.429809        368.452079
28  29.0   0.003581 -8.956410e-03  685.280287  827920.429809        368.452079
29  30.0   0.007419 -8.956410e-03  685.280287  827920.429809        368.452079
30  31.0   0.003581 -3.601640e-03  685.280287  827920.429809        368.452079
31  32.0   0.007419 -3.601640e-03  685.280287  827920.429809        368.452079
32  33.0   0.001000 -6.279025e-03  600.000000  700000.000000        345.000000
33  34.0   0.010000 -6.279025e-03  600.000000  700000.000000        345.000000
34  35.0   0.005500 -1.255805e-02  600.000000  700000.000000        345.000000
35  36.0   0.005500 -2.363726e-13  600.000000  700000.000000        345.000000
36  37.0   0.005500 -6.279025e-03  400.000000  700000.000000        345.000000
37  38.0   0.005500 -6.279025e-03  800.000000  700000.000000        345.000000
38  39.0   0.005500 -6.279025e-03  600.000000  400000.000011        345.000000
39  40.0   0.005500 -6.279025e-03  600.000000  999999.999989        345.000000
40  41.0   0.005500 -6.279025e-03  600.000000  700000.000000        290.000000
41  42.0   0.005500 -6.279025e-03  600.000000  700000.000000        400.000000
42  43.0   0.005500 -6.279025e-03  600.000000  700000.000000        345.000000